/**
 * Generated by tsnapi — public API snapshot of `actionspack`
 */
// #region Interfaces
export interface ActionspackConfig {
  entries: WorkflowEntry[];
  external: string[];
}
export interface ActionspackOptions {
  cwd?: string;
  entries?: WorkflowEntry[];
  external?: string[];
  github?: GitHubClient;
  stdout?: WritableStream;
  stderr?: WritableStream;
}
export interface CommandResult {
  lockfile: Lockfile;
  entries: WorkflowEntry[];
}
export interface DiffOptions extends ActionspackOptions {
  json?: boolean;
}
export interface DiffResult {
  added: string[];
  removed: string[];
  changed: Array<{
    package: string;
    oldResolved: string;
    newResolved: string;
    dependencyChanged: boolean;
  }>;
}
export interface GitHubClient {
  resolveRef: (_: string, _: string, _: string) => Promise<string>;
  readFile: (_: string, _: string, _: string, _: string) => Promise<string | undefined>;
}
export interface LockDependency {
  package: string;
  requested: string;
  resolved?: string;
  foundAt?: string;
}
export interface LockEntry {
  output: string;
  dependencies: LockDependency[];
}
export interface Lockfile {
  lockfileVersion: 1;
  entries: Record<string, LockEntry>;
  packages: Record<string, LockPackage>;
}
export interface LockPackage {
  source: "github";
  owner: string;
  repo: string;
  path: string;
  requested: string;
  resolved: string;
  type: "composite" | "external-action" | "external-workflow" | "reusable-workflow";
  external?: boolean;
  contentDigest: string;
  dependencies: LockDependency[];
}
export interface UpdateOptions extends ActionspackOptions {
  packageName?: string;
  lockfileOnly?: boolean;
}
export interface WorkflowEntry {
  source: string;
  output: string;
}
// #endregion

// #region Functions
export declare function assertNoRemoteUses(_: unknown, _?: string): void;
export declare function collectStepDependencies(_: unknown[], _: string): ResolvedDependency[];
export declare function collectWorkflowDependencies(_: Record<string, unknown>, _: string): ResolvedDependency[];
export declare function diff(_?: DiffOptions): Promise<DiffResult | string>;
export declare function diffLockfiles(_: Lockfile, _: Lockfile): DiffResult;
export declare function pack(_?: ActionspackOptions): Promise<CommandResult>;
export declare function packWorkflow(_: Record<string, unknown>, _: Lockfile, _: GitHubClient): Promise<Record<string, unknown>>;
export declare function scan(_?: ScanOptions): Promise<CommandResult>;
export declare function tree(_?: ActionspackOptions): Promise<string>;
export declare function update(_?: UpdateOptions): Promise<void>;
export declare function verify(_?: ActionspackOptions): Promise<CommandResult>;
export declare function why(_: string, _?: ActionspackOptions): Promise<string>;
// #endregion